### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by chiragmittal19** [chiragmittal19/Diamond-Shape#6]
Please add a short Readme.md file for this project

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.

**Comment by Subway19** [comment]
Specify the details to include in README.md file

**Comment by JingMa87** [comment]
Thanks for participating in Hacktoberfest. ;)

**Comment by JuanRodriguez32** [comment]
Can I help?

**Comment by chiragmittal19** [comment]
Thank you Juan for coming forward. Although I am closing this issue, but you are always welcome.
You can have a look at **[this](https://github.com/Book-Store/book-store.github.io)** repo.
Feel free to contribute. :)
